# Generated by Django 4.0.4 on 2022-05-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
