# Generated by Django 4.0.4 on 2022-05-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starttime',
        ),
    ]
