# Generated by Django 4.0.4 on 2022-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_remove_event_endtime_remove_event_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('capacity', models.CharField(max_length=2)),
            ],
        ),
    ]
