# Generated by Django 4.0.4 on 2022-05-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.event'),
        ),
    ]
