# Generated by Django 4.0.4 on 2022-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0008_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[{1, 'Studio'}], default='', max_length=100),
        ),
    ]
