# Generated by Django 4.0.4 on 2022-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[{0, 'Studio'}, {1, 'Mixing Room'}], default='', max_length=100),
        ),
    ]
