# Generated by Django 4.0.4 on 2022-05-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0013_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
    ]
