# Generated by Django 4.0.4 on 2022-05-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0015_type_remove_room_category_delete_category_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
