# Generated by Django 4.0.4 on 2022-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0016_event_endtime_event_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', 'Microphone'), ('2', 'DI Box')], default='1', max_length=2)),
            ],
        ),
    ]
