# Generated by Django 4.0.4 on 2022-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0017_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.IntegerField(default=800000),
        ),
    ]
