# Generated by Django 4.0.4 on 2022-05-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0018_item_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
