# Generated by Django 4.0.4 on 2022-05-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0021_itemtype_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.itemarea'),
        ),
    ]
