# Generated by Django 4.0.4 on 2022-05-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingsystem', '0022_itemarea_item_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebooked', models.DateTimeField(auto_now_add=True)),
                ('collectiontime', models.DateTimeField(blank=True, null=True)),
                ('returntime', models.DateTimeField(blank=True, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
