# Generated by Django 4.0.4 on 2022-05-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0024_reservation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='items',
            new_name='item',
        ),
    ]
