# Generated by Django 4.0.4 on 2022-05-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0025_rename_items_reservation_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='item',
            new_name='items',
        ),
    ]
