# Generated by Django 4.0.4 on 2022-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0026_rename_item_reservation_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='items',
        ),
        migrations.AddField(
            model_name='reservation',
            name='items',
            field=models.ManyToManyField(to='bookingsystem.item'),
        ),
    ]
